export * from './FriendsPage/FriendsPage';
export * from './LoginPage/LoginPage';
export * from './NewsfeedPage/NewsfeedPage';
export * from './NotFoundPage/NotFoundPage';
export * from './ProfilePage/ProfilePage';
export * from './RegistrationPage/RegistrationPage';
export * from './EditProfilePage/EditProfile';
export * from './MainLayout/MainLayout';
export * from './SearchPage/SearchPage';